version: "3"
services:
  web:
    build: .
    image: "api2"
    ports:  
      - "3000:3000"

    volumes:
      - "C:/Users/Matias/Documents/api2:/api2"
    
    links: 
      - "db:redis"
  
  db: 
    image: "redis"

    ports: 
     - '6379:6379'





# services:
#         web:
#           build: .
#           command: sh -c 'npm install; npm start'
#           ports:
#               - '3000:3000'
#           volumes:
#               - C:\Users\Matias\Documents\api2:\api2
#           links:
#               - "db:redis"
#         db:
#           image: redis
#           ports: 
#               - '6379:6379'